[package]
name = "rustyos"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[workspace]
members = ["kernel"]

[build-dependencies]
bootloader = "0.11.4"
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }

[dependencies]
